### ISSUE TITLE
REQUEST 

### ISSUE THREAD

**Issue by ghost** [ITZ-ZAID/mogenius#1]
Is it working for you sir

**Comment by ITZ-ZAID** [comment]
Yeah

**Comment by ghost** [comment]
I can't use 
Can save restricted conent bit work on it

**Comment by ITZ-ZAID** [comment]
Actually issue is?

**Comment by itzharshit** [comment]
Save Restricted Contents bot will not work on mogenius cos they offer limited bandwidth and this type of bots require high amount of bandwidth.

**Comment by ITZ-ZAID** [comment]
No idea
